name: comic_optimizer
description: "A simple GUI to optimize comics with pingo."
publish_to: "none"
version: 0.0.2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  shared_preferences: ^2.1.5
  archive: ^4.0.7
  path: ^1.8.3
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
